### ISSUE TITLE
[Bug Fix] STT 변환페이지에서 업로드 시 파일명이 사라지는 이슈

### ISSUE THREAD

**Issue by KimJaeGeun297** [tmax-aips/superbrain#27]
2022-05-25 [Bug Fix] STT 변환 페이지에서 업로드 시 파일명이 사라지는 이슈

- [x] STT 변환페이지에서 업로드 시 파일명 사라지는 이슈

**Comment by jeonggeun-jang** [comment]
2022-05-26 complete

closed issue
