### ISSUE TITLE
[기능개선] Text Drag 기능 개선

### ISSUE THREAD

**Issue by KimJaeGeun297** [tmax-aips/superbrain#8]
2022.05.20 [기능개선] Text Drag 방지 기능 추가

- [x] 홈 텍스트 드래그 방지
- [x] STT 텍스트 드래그 방지
- [x] VideoCaption 텍스트 드래그 방지
- [x] TTS 텍스트 드래그 방지

**Comment by jeonggeun-jang** [comment]
2022-05-24 complete
